Repository deskflow/deskflow, pull requests merged in 2024-10, with the labels that each got.

#7651 fix: Set correct QGuiApplication::desktopFileName
  src/gui/src/main.cpp
Labels: enhancement

#7666 Remove dead `test-dist-upload.yml` file
  .github/workflows/test-dist-upload.yml
Labels: ci

#7675 Fixed error count logic for test summary
  .github/actions/test-summary/action.yml
  .github/workflows/test-actions.yml
Labels: enhancement, ci

#7693 fix: Check for errors before reading version string
  src/lib/gui/VersionChecker.cpp
Labels: bug

#7690 ci: clearer and cleaner steps
  .github/workflows/ci.yml
Labels: enhancement, ci

#7697 Ignore paths for CodeQL Analysis
  .github/workflows/codeql-analysis.yml
Labels: enhancement, ci

#7702 Always run PR comments job
  .github/workflows/ci.yml
Labels: bug, ci

#7711 Remove Wayland experimental pop
  src/lib/gui/core/WaylandWarnings.cpp
  src/lib/gui/core/WaylandWarnings.h
  src/lib/gui/messages.cpp
  src/lib/gui/messages.h
  src/test/unittests/gui/core/WaylandWarningsTests.cpp
Labels: enhancement

#7689 build: linux packages with proper names using cpack
  .github/workflows/ci-linux.json
  .github/workflows/ci.yml
  cmake/Packaging.cmake
Labels: enhancement, ci

#7761 fix:#7760 use a proper fedora package name
  cmake/Packaging.cmake
Labels: ci

#7757 ci: Normalize CI step names, descriptions, etc
  .github/actions/add-kitware-repo/action.yml
  .github/workflows/ci.yml
  cspell.json
Labels: nit

#7834 doc: correct target for documents
  CMakeLists.txt
  doc/CMakeLists.txt
Labels: bug
