Repository deskflow/deskflow, pull requests merged in 2024-12, with the labels that each got.

#7944 ReAdd NDEBUG define
  CMakeLists.txt
Labels: bug

#7959 Fixed UTF-16 surrogate handling
  src/lib/base/Unicode.cpp
Labels: enhancement

#7991 fix: #7942, Correctly substitute config name part
  src/lib/server/Config.cpp
Labels: bug

#7990 Fix: #7940 and #7941
  src/lib/deskflow/ServerApp.h
Labels: bug

#8002 fix: Mac os gui nits
  src/apps/deskflow-gui/MainWindow.cpp
Labels: bug, macos

#8020 refactor: Copy the full version string on the about dialog
  src/apps/deskflow-gui/dialogs/AboutDialog.cpp
  src/apps/deskflow-gui/dialogs/AboutDialog.h
Labels: enhancement

#8018 fix: 8017, move wayland notes to debug context
  src/lib/platform/EiKeyState.cpp
  src/lib/platform/EiScreen.cpp
Labels: enhancement

#8019 fix: Unify both Quit actions to use the same function
  src/apps/deskflow-gui/MainWindow.cpp
  src/apps/deskflow-gui/MainWindow.h
Labels: bug, macos
