Repository deskflow/deskflow, pull requests merged in 2025-01, with the labels that each got.

#8022 fix: The Tls Fingerprint label not being shown on start up
  src/apps/deskflow-gui/MainWindow.cpp
  src/apps/deskflow-gui/MainWindow.ui
Labels: bug

#8023 fix: Wayland Prompt starts under MainWindow
  src/apps/deskflow-gui/MainWindow.cpp
Labels: bug

#8034 Proper hide to tray
  src/apps/deskflow-gui/MainWindow.cpp
  src/apps/deskflow-gui/MainWindow.h
  src/lib/gui/OSXHelpers.h
  src/lib/gui/OSXHelpers.mm
Labels: enhancement

#8037 Run MacDeployQt at install time on staged app only
  deploy/mac/deploy.cmake
  src/apps/deskflow-gui/CMakeLists.txt
Labels: enhancement, macos

#8042 Macos Sign the App with local cert
  deploy/mac/deploy.cmake
Labels: enhancement, macos

#8047 Hotkey fix
  src/apps/deskflow-gui/Hotkey.cpp
  src/apps/deskflow-gui/Hotkey.h
Labels: bug, enhancement

#8046 fix: messages read into vector are cut off by 4 bytes
  src/lib/deskflow/ProtocolUtil.cpp
  src/lib/deskflow/ProtocolUtil.h
Labels: bug, regression

#8027 Allow only one instance of the gui
  src/apps/deskflow-gui/MainWindow.cpp
  src/apps/deskflow-gui/MainWindow.h
  src/apps/deskflow-gui/main.cpp
Labels: enhancement

#8044 Port Action improvements from IL
  src/apps/deskflow-gui/Action.cpp
  src/apps/deskflow-gui/Action.h
Labels: enhancement

#8101 CI: Build Arm Packages for Debian, Fedora and Opensuse
  .github/workflows/continuous-integration.yml
Labels: ci

#8116 ci: add builder for ubuntu 25.04
  .github/workflows/continuous-integration.yml
Labels: ci, new platform

#8141 refactor: force mac os to use the larger security icon for the status area
  src/apps/deskflow-gui/MainWindow.cpp
Labels: bug, macos

#8098 Add FingerPrint DB
  src/lib/base/CMakeLists.txt
  src/lib/base/finally.h
  src/lib/io/CMakeLists.txt
  src/lib/io/filesystem.cpp
  src/lib/io/filesystem.h
  src/lib/io/win32/encoding_utilities.cpp
  src/lib/io/win32/encoding_utilities.h
  src/lib/net/CMakeLists.txt
  src/lib/net/FingerprintData.cpp
  src/lib/net/FingerprintData.h
  src/lib/net/FingerprintDatabase.cpp
  src/lib/net/FingerprintDatabase.h
Labels: 💰 rewarded
