Repository deskflow/deskflow, pull requests merged in 2025-05, with the labels that each got.

#8503 Fix: Cursor stuck off server screen (Wayland, attempt)
  src/lib/platform/EiScreen.cpp
Labels: 🙋 bounty claim

#8563 Deskflow-gui add `reset` option
  src/apps/deskflow-gui/deskflow-gui.cpp
  src/lib/gui/Diagnostic.cpp
Labels: ✨ enhancement

#8566 Tidy up macos code smells missed by sonarscan
  src/lib/platform/OSXClipboard.h
  src/lib/platform/OSXClipboardAnyBitmapConverter.cpp
  src/lib/platform/OSXClipboardAnyBitmapConverter.h
  src/lib/platform/OSXClipboardAnyTextConverter.cpp
  src/lib/platform/OSXClipboardAnyTextConverter.h
  src/lib/platform/OSXClipboardBMPConverter.cpp
  src/lib/platform/OSXClipboardBMPConverter.h
  src/lib/platform/OSXClipboardHTMLConverter.cpp
  src/lib/platform/OSXClipboardHTMLConverter.h
  src/lib/platform/OSXClipboardTextConverter.cpp
  src/lib/platform/OSXClipboardTextConverter.h
  src/lib/platform/OSXClipboardUTF16Converter.cpp
  src/lib/platform/OSXClipboardUTF16Converter.h
  src/lib/platform/OSXClipboardUTF8Converter.h
  src/lib/platform/OSXEventQueueBuffer.cpp
  src/lib/platform/OSXEventQueueBuffer.h
  src/lib/platform/OSXKeyState.cpp
  src/lib/platform/OSXKeyState.h
  src/lib/platform/OSXPowerManager.cpp
  src/lib/platform/OSXPowerManager.h
  src/lib/platform/OSXScreenSaver.h
  src/lib/platform/OSXUchrKeyResource.h
Labels: :apple: mac, :spiral_notepad: task

#8567 Better detect windows Arm64 on both CI and local builds
  CMakeLists.txt
Labels: 🪟 windows

#8581 sync arch package depends those used on arch
  deploy/linux/arch/PKGBUILD.in
Labels: :robot: ci, :pick: nit

#8608 ci: Simplify our `Install Dependencies` action
  .github/actions/install-dependencies/action.yml
Labels: :robot: ci

#8617 Consolidate arch strings
  src/lib/arch/Arch.h
  src/lib/arch/ArchString.cpp
  src/lib/arch/ArchString.h
  src/lib/arch/CMakeLists.txt
  src/lib/arch/unix/ArchStringUnix.cpp
  src/lib/arch/unix/ArchStringUnix.h
  src/lib/arch/win32/ArchStringWindows.cpp
  src/lib/arch/win32/ArchStringWindows.h
  src/lib/base/Unicode.cpp
  src/lib/base/Unicode.h
  src/unittests/arch/ArchStringTests.cpp
  src/unittests/arch/ArchStringTests.h
  src/unittests/arch/CMakeLists.txt
  src/unittests/base/UnicodeTests.cpp
Labels: :spiral_notepad: task

#8613 Log Error and stop the core process if print database is not writable
  src/lib/gui/MainWindow.cpp
Labels: :spiral_notepad: task
