Repository deskflow/deskflow, pull requests merged in 2025-04, with the labels that each got.

#8431 Portable windows build
  deploy/windows/cpack-options.cmake.in
  deploy/windows/deploy.cmake
  deploy/windows/pre-cpack.cmake.in
Labels: 🪄 feature request

#8440 Manpages
  .github/actions/install-dependencies/action.yml
  REUSE.toml
  src/apps/CMakeLists.txt
  src/apps/deskflow-client/CMakeLists.txt
  src/apps/deskflow-core/CMakeLists.txt
  src/apps/deskflow-gui/CMakeLists.txt
  src/apps/deskflow-gui/deskflow.man.template.in
  src/apps/deskflow-server/CMakeLists.txt
  src/apps/res/manpage.txt
Labels: 📝 document, :rewind: regression

#8464 fixes #8463 do not assume C for root
  src/lib/common/Settings.h
Labels: 🪟 windows, 🩹 fix

#8515 ci: add builder for fedora 42
  .github/workflows/continuous-integration.yml
Labels: :robot: ci

#8509 fix: user can not start in client mode without a remote host
  src/lib/gui/MainWindow.cpp
  src/lib/gui/MainWindow.h
Labels: 🩹 fix

#8510 Remove unused old test mocks
  src/test/mock/server/MockServer.h
  src/test/shared/gui/TestQtFullApp.h
Labels: :spiral_notepad: task

#8511 Remove more code for inverse connection
  src/lib/deskflow/ServerApp.cpp
  src/lib/server/ClientListener.cpp
  src/lib/server/ClientListener.h
  src/lib/server/Config.cpp
  src/lib/server/Config.h
  src/lib/server/Server.cpp
  src/lib/server/Server.h
Labels: :spiral_notepad: task

#8518 Save the host name if the lineEdit is not empty
  src/lib/gui/MainWindow.cpp
Labels: 🩹 fix

#8454 Rm switchon desk
  src/apps/deskflow-server/deskflow-server.cpp
  src/lib/common/Settings.cpp
  src/lib/common/Settings.h
  src/lib/deskflow/ArgParser.cpp
  src/lib/deskflow/ArgsBase.h
  src/lib/deskflow/ClientApp.cpp
  src/lib/deskflow/ServerApp.cpp
  src/lib/gui/core/CoreProcess.cpp
  src/lib/gui/dialogs/SettingsDialog.cpp
  src/lib/gui/dialogs/SettingsDialog.ui
  src/lib/platform/MSWindowsDesks.cpp
  src/lib/platform/MSWindowsDesks.h
  src/lib/platform/MSWindowsScreen.cpp
  src/lib/platform/MSWindowsScreen.h
  src/lib/platform/MSWindowsWatchdog.cpp
  src/lib/platform/MSWindowsWatchdog.h
Labels: 🪟 windows

#8535 ensure client, server and core use correct setting path
  src/apps/deskflow-client/deskflow-client.cpp
  src/apps/deskflow-core/deskflow-core.cpp
  src/apps/deskflow-server/deskflow-server.cpp
Labels: 🪟 windows, 🩹 fix

#8541 ci: use normal built in vcpkg cache
  .github/actions/install-dependencies/action.yml
Labels: :robot: ci
