Repository deskflow/deskflow, pull requests merged in 2025-03, with the labels that each got.

#8337 chore: Rename TLS constants for consistency
  src/apps/deskflow-gui/MainWindow.cpp
  src/lib/common/constants.h.in
  src/lib/gui/paths.h
  src/lib/gui/tls/TlsCertificate.cpp
  src/lib/net/SecureSocket.cpp
Labels: nit

#8408 fix: local-fingerprint generation
  src/lib/gui/tls/TlsCertificate.cpp
Labels: bug

#8420 chore: use Type for templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: document
