Repository deskflow/deskflow, pull requests merged in 2025-08, with the labels that each got.

#8817 ci: Use reuse-actionv5
  .github/workflows/continuous-integration.yml
Labels: :spiral_notepad: task

#8814 fix: Account for more modifiers in the EI keymap calculation
  src/lib/platform/EiKeyState.cpp
Labels: wayland

#8837 fix: MainWindow::setHostName potental error
  src/lib/gui/MainWindow.cpp
Labels: ✨ enhancement, 🩹 fix

#8894 ci: use action checkout v5
  .github/workflows/continuous-integration.yml
Labels: :robot: ci
